import Head from 'next/head'
import Image from 'next/image'
import Header from './component/header'
import Link from 'next/link'

export default function Home() {
  return (
    <div className='container max-w-screen-2xl m-auto shadow'>
      <Head>
        <title >Twilio_Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/home.ico" />
      </Head>

      <main >
        <Header/>
      </main>

      
    </div>
  )
}
